#!/bin/sh

# check args count
if [ $# -ne 1 ]; then
  echo "Usage : $0 <kickstart file>"
  exit
fi

# check require packages
reqpkgs="lorax-lmc-novirt lorax-templates-rhel patch"
ninstpkgs=""
cnt=0

for pkg in ${reqpkgs}
do
  rpm -q ${pkg} > /dev/null
  if [ $? -ne 0 ]; then
    ninstpkgs="${ninstpkgs}${pkg} "
    cnt=`expr ${cnt} "+" 1`
  fi
done

if [ ${cnt} -ne 0 ]; then
  echo "require packages: ${ninstpkgs}"
  exit
fi

# check kickstart files
kickstart=${1}
if [ ! -f ${kickstart} ]; then
  echo "${kickstart} is not exist."
  exit
fi

logfile=${0}-`date +%Y%m%d%H%M%S`.log
logdir=logs
temp=tmp
resultdir=results
tmpldir=live-tmpl

if [ ! -d ${temp} ]; then
  mkdir -p ${temp}
fi

if [ ! -d ${logdir} ]; then
  mkdir -p ${logdir}
fi

if [ ! -d ${tmpldir} ]; then
  cp -aR /usr/share/lorax/templates.d/80-rhel/ live-tmpl/
  patch -u -p1 -d live-tmpl < c8-live-tmpl.patch
fi

livemedia-creator \
--ks ${kickstart} \
--lorax-templates ${tmpldir} \
--no-virt \
--iso-only \
--make-iso \
--nomacboot \
--volid CentOS-8-1905 \
--iso-name "CentOS-8-x86_64-1905-LiveGNOME.iso" \
--title "CentOS Live Linux 8.0 1905 (JP)" \
--project "CentOS Live Linux" \
--releasever "8\.0\ 1905\ \(JP\)" \
--fs-label "CentOS-8-x86_64" \
--extra-boot-args noswap \
--tmp ${temp} \
--resultdir ./${resultdir} \
--logfile ${logdir}/${logfile}

ret=$?
if [ ${ret} -ne 0 ]; then
  echo "livemedia-creator is failed"
  exit
fi
